# Generated by Django 2.1.2 on 2018-11-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_komuna', models.SmallIntegerField(unique=True)),
                ('emri_komuna', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vendi', models.SmallIntegerField(unique=True)),
                ('emri_vendi', models.CharField(max_length=50, unique=True)),
                ('komuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.Komuna')),
            ],
        ),
    ]
