# Generated by Django 2.1.2 on 2018-12-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_citypark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Religions',
            new_name='Religion',
        ),
    ]
