# Generated by Django 2.1.2 on 2018-12-22 20:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_auto_20181220_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
            ],
        ),
    ]
