# Generated by Django 2.1.2 on 2018-12-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_geoobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoObject',
        ),
    ]
