# Generated by Django 2.1.2 on 2019-01-04 18:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2090, unique=True)),
                ('location', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AllLayers',
            },
        ),
        migrations.DeleteModel(
            name='Layers',
        ),
    ]
